### ISSUE TITLE
how can i understand if message is gone

### ISSUE THREAD

**Issue by dolmushcu** [aalsuwaidi/wabot#13]
how can i understand if message is gone

**Comment by aalsuwaidi** [comment]
Not sure what you mean? As in how do you know if the message is delivered / seen etc.?

**Comment by dolmushcu** [comment]
Yes i mean if number is exsit

**Comment by dolmushcu** [comment]
And i solve this problem with this code
 if(Store.Chat.find(jid)){  }

**Comment by aalsuwaidi** [comment]
Ah that makes sense,

A cleaner way to do it would be to use the following:

`Store.Chat.find(jid).then((chat) => { //This chat exists
})`

If the number isn't on WhatsApp or there is an error you can use the catch method like this:
`Store.Chat.find(jid).then((chat) => {}).catch((error) => {})`
